import {Geist, Geist_Mono, Oswald} from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";
import CookieConsentWrapper from "./components/commons/CookieConsentWrapper"; // Import normal

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const oswald = Oswald({
    subsets: ["latin"],
    variable: "--font-oswald",
    weight: ["200", "300", "400", "500", "700"],
    display: "swap",
});

export const metadata = {
    title: "AR Real Estate Media",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{ children: React.ReactNode }>) {

    return (
        <html lang="en">
        <body className={`${oswald.variable} antialiased`}>
        {/* Render CookieConsent doar pe client */}
        <CookieConsentWrapper/>

        <Navbar/>
        {children}
        <Footer/>
        </body>
        </html>
    );
}
